### PR TITLE
Swift & Moved SDWebImage to subspec

### LINKED ISSUE #14: Fade black background view alpha when dragging to close
As the user drags an image down to close the image viewer, I'm thinking it might be nice to also fade the alpha transparency of the container's background view as well to better educate the user that they're closing out the image.

### LINKED ISSUE #35: Decouple retrieveImageFromURL
Remove SDWebImage as dependency.

Done. I'll submit a PR later.

Update: Closing issue for now.

### PR DESCRIPTION
**Pull request by bre7**
* Swift rewrite
 * Refactored `retrieveImageFromURL` to a protocol
   * Moved SDWebImage to new subspec (`pod 'BFRImageViewer/SDWebImage'`).
 * Renamed `BFR...` classes to `Buffer...`
 * Updated docs to markdown format
* Added fade animation (#14) (considering `containerView.y` <~> `gesture.y` distance)
* Removed `BFRImageViewerDemo/Pods/` subdir from the repo

TODO: Apply API Design guidelines

Closes #35
Closes #14

**Update**: Maintain ObjC and Swift versions of the pod ? It's not that hard to remove AnyObject in favor of a type-safe approach (like an enum). The issue is objc compatibility.

### CODE REVIEW

**Comment by DreamingInBinary** [comment]
Hey hey @bre7 - awesome stuff 😄 Sorry for the delay on reviewing this - we've been pushing to get some larger projects ready for the world! @ay8s or I will have a look asap 👍

**Comment by bre7** [comment]
Awesome 👍

**Comment by DreamingInBinary** [comment]
Hey hey @bre7 - so sorry for the delay here and thanks for all your hard work! At Buffer - we aren't quite moving to Swift yet (likely won't until ABI compatibility hits), I was wondering if you'd be up for moving this PR over to the 'release/swift' branch as we'd love to have a Swift rewrite in another location 👍

**Comment by bre7** [comment]
Hey Jordan, I'll resend it ;)

**Pull request closed without merging**
